classDiagram
direction LR
    class AudioBox{
        bool entered
        AnimationPlayer animation_player
        Label tooltip
        _process()
        _on_body_entered()
        _on_body_exited()
    }