flowchart LR
    user
    enemy((move enemy))
    player((player action))
    move((move player))
    place-dot((place dot))
    mine((mine))
    audiobox((play audio))
    stairs((move floor))
    teleport-enemy((teleport enemy))
    save-load((save load))
    save-file@{ shape: datastore, label: "save file" }
    user --> |input| move
    user --> |player pos, distraction mine pos, markers pos| enemy
    user --> |input| player
    player --> |angle, position, is_shotgun_bullet| place-dot
    player --> |position| mine((place mine))
    mine-shoot((shoot mine)) --> |angle, position| place-dot
    place-dot --> |shot| enemy
    user --> |input| audiobox
    user --> |input| stairs
    player --> |player pos| teleport-enemy
    teleport-enemy --> |location| enemy
    mine --> |hearable| enemy
    player --> |hearable| enemy
    user --> |player_data, colours, settings| save-load
    save-load --> |save_data| save-file
    save-file --> |save_data| save-load